window.BENGALI_BASE_CONTENT = {
  script: [
    { group: 'Vowels', bengali: 'অ', roman: 'ô', devanagari: 'अ', tamil: 'அ', example: 'অমর', exampleRoman: 'ômor', meaning: 'immortal' },
    { group: 'Vowels', bengali: 'আ', roman: 'ā', devanagari: 'आ', tamil: 'ஆ', example: 'আম', exampleRoman: 'ām', meaning: 'mango' },
    { group: 'Vowels', bengali: 'ই', roman: 'i', devanagari: 'इ', tamil: 'இ', example: 'ইচ্ছা', exampleRoman: 'icchā', meaning: 'wish' },
    { group: 'Vowels', bengali: 'ঈ', roman: 'ī', devanagari: 'ई', tamil: 'ஈ', example: 'ঈশ্বর', exampleRoman: 'īśvar', meaning: 'God' },
    { group: 'Vowels', bengali: 'উ', roman: 'u', devanagari: 'उ', tamil: 'உ', example: 'উৎসব', exampleRoman: 'utsôb', meaning: 'festival' },
    { group: 'Vowels', bengali: 'ঊ', roman: 'ū', devanagari: 'ऊ', tamil: 'ஊ', example: 'ঊষা', exampleRoman: 'ūṣā', meaning: 'dawn' },
    { group: 'Vowels', bengali: 'ঋ', roman: 'ri', devanagari: 'ऋ', tamil: 'ரு', example: 'ঋষি', exampleRoman: 'riṣi', meaning: 'sage' },
    { group: 'Vowels', bengali: 'এ', roman: 'e', devanagari: 'ए', tamil: 'ஏ', example: 'এক', exampleRoman: 'ek', meaning: 'one' },
    { group: 'Vowels', bengali: 'ঐ', roman: 'oi', devanagari: 'ऐ', tamil: 'ஐ', example: 'ঐক্য', exampleRoman: 'oikyo', meaning: 'unity' },
    { group: 'Vowels', bengali: 'ও', roman: 'o', devanagari: 'ओ', tamil: 'ஓ', example: 'ওষুধ', exampleRoman: 'oṣudh', meaning: 'medicine' },
    { group: 'Vowels', bengali: 'ঔ', roman: 'ou', devanagari: 'औ', tamil: 'ஔ', example: 'ঔষধ', exampleRoman: 'ouṣôdh', meaning: 'medicine' },

    { group: 'Consonants', bengali: 'ক', roman: 'ka', devanagari: 'क', tamil: 'க', example: 'কাজ', exampleRoman: 'kāj', meaning: 'work' },
    { group: 'Consonants', bengali: 'খ', roman: 'kha', devanagari: 'ख', tamil: 'க்ஹ', example: 'খাবার', exampleRoman: 'khābār', meaning: 'food' },
    { group: 'Consonants', bengali: 'গ', roman: 'ga', devanagari: 'ग', tamil: 'க', example: 'গান', exampleRoman: 'gān', meaning: 'song' },
    { group: 'Consonants', bengali: 'ঘ', roman: 'gha', devanagari: 'घ', tamil: 'க்ஹ', example: 'ঘর', exampleRoman: 'ghôr', meaning: 'room' },
    { group: 'Consonants', bengali: 'ঙ', roman: 'ṅa', devanagari: 'ङ', tamil: 'ங', example: 'বাংলা', exampleRoman: 'bāṅlā', meaning: 'Bengali' },
    { group: 'Consonants', bengali: 'চ', roman: 'ca', devanagari: 'च', tamil: 'ச', example: 'চাল', exampleRoman: 'cāl', meaning: 'rice' },
    { group: 'Consonants', bengali: 'ছ', roman: 'cha', devanagari: 'छ', tamil: 'ச்ஹ', example: 'ছোট', exampleRoman: 'choṭo', meaning: 'small' },
    { group: 'Consonants', bengali: 'জ', roman: 'ja', devanagari: 'ज', tamil: 'ஜ', example: 'জল', exampleRoman: 'jôl', meaning: 'water' },
    { group: 'Consonants', bengali: 'ঝ', roman: 'jha', devanagari: 'झ', tamil: 'ஜ்ஹ', example: 'ঝাল', exampleRoman: 'jhāl', meaning: 'spicy' },
    { group: 'Consonants', bengali: 'ঞ', roman: 'ña', devanagari: 'ञ', tamil: 'ஞ', example: 'পঞ্চ', exampleRoman: 'pônco', meaning: 'fivefold' },
    { group: 'Consonants', bengali: 'ট', roman: 'ṭa', devanagari: 'ट', tamil: 'ட', example: 'টাকা', exampleRoman: 'ṭākā', meaning: 'money' },
    { group: 'Consonants', bengali: 'ঠ', roman: 'ṭha', devanagari: 'ठ', tamil: 'ட்ஹ', example: 'ঠাকুর', exampleRoman: 'ṭhākur', meaning: 'deity/master' },
    { group: 'Consonants', bengali: 'ড', roman: 'ḍa', devanagari: 'ड', tamil: 'ட', example: 'ডাল', exampleRoman: 'ḍāl', meaning: 'lentils' },
    { group: 'Consonants', bengali: 'ঢ', roman: 'ḍha', devanagari: 'ढ', tamil: 'ட்ஹ', example: 'ঢাকা', exampleRoman: 'ḍhākā', meaning: 'Dhaka' },
    { group: 'Consonants', bengali: 'ণ', roman: 'ṇa', devanagari: 'ण', tamil: 'ண', example: 'গণেশ', exampleRoman: 'gôṇeś', meaning: 'Ganesha' },
    { group: 'Consonants', bengali: 'ত', roman: 'ta', devanagari: 'त', tamil: 'த', example: 'তুমি', exampleRoman: 'tumi', meaning: 'you' },
    { group: 'Consonants', bengali: 'থ', roman: 'tha', devanagari: 'थ', tamil: 'த்ஹ', example: 'থালা', exampleRoman: 'thālā', meaning: 'plate' },
    { group: 'Consonants', bengali: 'দ', roman: 'da', devanagari: 'द', tamil: 'த', example: 'দুধ', exampleRoman: 'dudh', meaning: 'milk' },
    { group: 'Consonants', bengali: 'ধ', roman: 'dha', devanagari: 'ध', tamil: 'த்ஹ', example: 'ধন্যবাদ', exampleRoman: 'dhônyobād', meaning: 'thank you' },
    { group: 'Consonants', bengali: 'ন', roman: 'na', devanagari: 'न', tamil: 'ந', example: 'নমস্কার', exampleRoman: 'nômôskār', meaning: 'greetings' },
    { group: 'Consonants', bengali: 'প', roman: 'pa', devanagari: 'प', tamil: 'ப', example: 'পূজা', exampleRoman: 'pūjā', meaning: 'worship' },
    { group: 'Consonants', bengali: 'ফ', roman: 'pha/fa', devanagari: 'फ', tamil: 'ப்ஹ', example: 'ফল', exampleRoman: 'phôl', meaning: 'fruit' },
    { group: 'Consonants', bengali: 'ব', roman: 'ba', devanagari: 'ब', tamil: 'ப', example: 'বাড়ি', exampleRoman: 'bāṛi', meaning: 'home' },
    { group: 'Consonants', bengali: 'ভ', roman: 'bha', devanagari: 'भ', tamil: 'ப்ஹ', example: 'ভালো', exampleRoman: 'bhālo', meaning: 'good' },
    { group: 'Consonants', bengali: 'ম', roman: 'ma', devanagari: 'म', tamil: 'ம', example: 'মা', exampleRoman: 'mā', meaning: 'Mother' },
    { group: 'Consonants', bengali: 'য', roman: 'ya/ja', devanagari: 'य/ज', tamil: 'ய/ஜ', example: 'যাওয়া', exampleRoman: 'jāoẏā', meaning: 'to go' },
    { group: 'Consonants', bengali: 'র', roman: 'ra', devanagari: 'र', tamil: 'ர', example: 'রাস্তা', exampleRoman: 'rāstā', meaning: 'road' },
    { group: 'Consonants', bengali: 'ল', roman: 'la', devanagari: 'ल', tamil: 'ல', example: 'লাল', exampleRoman: 'lāl', meaning: 'red' },
    { group: 'Consonants', bengali: 'শ', roman: 'śa', devanagari: 'श', tamil: 'ஶ', example: 'শান্তি', exampleRoman: 'śānti', meaning: 'peace' },
    { group: 'Consonants', bengali: 'ষ', roman: 'ṣa', devanagari: 'ष', tamil: 'ஷ', example: 'কৃষ্ণ', exampleRoman: 'kriṣṇo', meaning: 'Krishna' },
    { group: 'Consonants', bengali: 'স', roman: 'sa', devanagari: 'स', tamil: 'ஸ', example: 'সকাল', exampleRoman: 'sôkāl', meaning: 'morning' },
    { group: 'Consonants', bengali: 'হ', roman: 'ha', devanagari: 'ह', tamil: 'ஹ', example: 'হরি', exampleRoman: 'hôri', meaning: 'Hari' },

    { group: 'Vowel signs', bengali: 'া', roman: 'ā', devanagari: 'ा', tamil: 'ா', example: 'মা', exampleRoman: 'mā', meaning: 'Mother' },
    { group: 'Vowel signs', bengali: 'ি', roman: 'i', devanagari: 'ि', tamil: 'ி', example: 'দিন', exampleRoman: 'din', meaning: 'day' },
    { group: 'Vowel signs', bengali: 'ী', roman: 'ī', devanagari: 'ी', tamil: 'ீ', example: 'দীপ', exampleRoman: 'dīp', meaning: 'lamp' },
    { group: 'Vowel signs', bengali: 'ু', roman: 'u', devanagari: 'ु', tamil: 'ு', example: 'তুমি', exampleRoman: 'tumi', meaning: 'you' },
    { group: 'Vowel signs', bengali: 'ূ', roman: 'ū', devanagari: 'ू', tamil: 'ூ', example: 'পূজা', exampleRoman: 'pūjā', meaning: 'worship' },
    { group: 'Vowel signs', bengali: 'ে', roman: 'e', devanagari: 'े', tamil: 'ே', example: 'দেশ', exampleRoman: 'deś', meaning: 'country' },
    { group: 'Vowel signs', bengali: 'ৈ', roman: 'oi', devanagari: 'ै', tamil: 'ை', example: 'তৈরি', exampleRoman: 'toiri', meaning: 'ready/made' },
    { group: 'Vowel signs', bengali: 'ো', roman: 'o', devanagari: 'ो', tamil: 'ோ', example: 'ভালো', exampleRoman: 'bhālo', meaning: 'good' },
    { group: 'Vowel signs', bengali: 'ৌ', roman: 'ou', devanagari: 'ौ', tamil: 'ௌ', example: 'নৌকা', exampleRoman: 'noukā', meaning: 'boat' },

    { group: 'Conjuncts', bengali: 'ক্ষ', roman: 'kṣa', devanagari: 'क्ष', tamil: 'க்ஷ', example: 'অক্ষর', exampleRoman: 'ôkkhôr', meaning: 'letter' },
    { group: 'Conjuncts', bengali: 'জ্ঞ', roman: 'jña/gya', devanagari: 'ज्ञ', tamil: 'ஜ்ஞ', example: 'জ্ঞান', exampleRoman: 'gyān', meaning: 'knowledge' },
    { group: 'Conjuncts', bengali: 'ত্র', roman: 'tra', devanagari: 'त्र', tamil: 'த்ர', example: 'ত্রিশ', exampleRoman: 'triś', meaning: 'thirty' },
    { group: 'Conjuncts', bengali: 'শ্র', roman: 'śra', devanagari: 'श्र', tamil: 'ஶ்ர', example: 'শ্রী', exampleRoman: 'śrī', meaning: 'Sri' },
    { group: 'Conjuncts', bengali: 'ন্দ', roman: 'nda', devanagari: 'न्द', tamil: 'ந்த', example: 'আনন্দ', exampleRoman: 'ānôndo', meaning: 'joy' },
    { group: 'Conjuncts', bengali: 'ম্প', roman: 'mpa', devanagari: 'म्प', tamil: 'ம்ப', example: 'সম্পূর্ণ', exampleRoman: 'sômpūrṇo', meaning: 'complete' },
    { group: 'Conjuncts', bengali: 'ক্ত', roman: 'kta', devanagari: 'क्त', tamil: 'க்த', example: 'ভক্তি', exampleRoman: 'bhôkti', meaning: 'devotion' },
    { group: 'Conjuncts', bengali: 'স্ত', roman: 'sta', devanagari: 'स्त', tamil: 'ஸ்த', example: 'রাস্তা', exampleRoman: 'rāstā', meaning: 'road' },
    { group: 'Conjuncts', bengali: 'চ্ছ', roman: 'ccha', devanagari: 'च्छ', tamil: 'ச்ச', example: 'ইচ্ছা', exampleRoman: 'icchā', meaning: 'wish' },
    { group: 'Conjuncts', bengali: 'প্র', roman: 'pra', devanagari: 'प्र', tamil: 'ப்ர', example: 'প্রসাদ', exampleRoman: 'prôśād', meaning: 'prasadam' }
  ],

  words: [
    { category: 'Greetings', bengali: 'নমস্কার', roman: 'nômôskār', devanagari: 'नमस्कार', tamil: 'நமஷ்கார்', meaning: 'Greetings / Namaskaram' },
    { category: 'Greetings', bengali: 'সুপ্রভাত', roman: 'suprôbhāt', devanagari: 'सुप्रभात', tamil: 'சுப்ரபாத்', meaning: 'Good morning' },
    { category: 'Greetings', bengali: 'শুভ রাত্রি', roman: 'śubho rātri', devanagari: 'शुभ रात्रि', tamil: 'ஶுபோ ராத்ரி', meaning: 'Good night' },
    { category: 'Greetings', bengali: 'ধন্যবাদ', roman: 'dhônyobād', devanagari: 'धन्यवाद', tamil: 'தொன்னோபாத்', meaning: 'Thank you' },
    { category: 'Greetings', bengali: 'দয়া করে', roman: 'dôẏā kore', devanagari: 'दया करे', tamil: 'தொயா கொரே', meaning: 'Please' },
    { category: 'Greetings', bengali: 'হ্যাঁ', roman: 'hyā̃', devanagari: 'हाँ', tamil: 'ஹ்யா', meaning: 'Yes' },
    { category: 'Greetings', bengali: 'না', roman: 'nā', devanagari: 'ना', tamil: 'நா', meaning: 'No' },

    { category: 'People', bengali: 'আমি', roman: 'āmi', devanagari: 'आमि', tamil: 'ஆமி', meaning: 'I' },
    { category: 'People', bengali: 'আপনি', roman: 'āpni', devanagari: 'आपनि', tamil: 'ஆப்னி', meaning: 'You (respectful)' },
    { category: 'People', bengali: 'তুমি', roman: 'tumi', devanagari: 'तुमि', tamil: 'துமி', meaning: 'You (familiar)' },
    { category: 'People', bengali: 'মা', roman: 'mā', devanagari: 'माँ', tamil: 'மா', meaning: 'Mother' },
    { category: 'People', bengali: 'বন্ধু', roman: 'bôndhu', devanagari: 'बन्धु', tamil: 'பொந்து', meaning: 'Friend' },

    { category: 'Questions', bengali: 'কি', roman: 'ki', devanagari: 'कि', tamil: 'கி', meaning: 'What' },
    { category: 'Questions', bengali: 'কে', roman: 'ke', devanagari: 'के', tamil: 'கே', meaning: 'Who' },
    { category: 'Questions', bengali: 'কোথায়', roman: 'kothāẏ', devanagari: 'कोथाय', tamil: 'கோதாய்', meaning: 'Where' },
    { category: 'Questions', bengali: 'কত', roman: 'kôto', devanagari: 'कतो', tamil: 'கொதோ', meaning: 'How much / how many' },
    { category: 'Questions', bengali: 'কেন', roman: 'keno', devanagari: 'केनो', tamil: 'கேனோ', meaning: 'Why' },
    { category: 'Questions', bengali: 'কখন', roman: 'kôkhôn', devanagari: 'कखन', tamil: 'கொகோன்', meaning: 'When' },

    { category: 'Daily', bengali: 'ভালো', roman: 'bhālo', devanagari: 'भालो', tamil: 'பாலோ', meaning: 'Good / well' },
    { category: 'Daily', bengali: 'আজ', roman: 'āj', devanagari: 'आज', tamil: 'ஆஜ்', meaning: 'Today' },
    { category: 'Daily', bengali: 'কাল', roman: 'kāl', devanagari: 'काल', tamil: 'கால்', meaning: 'Tomorrow / yesterday' },
    { category: 'Daily', bengali: 'এখন', roman: 'ekhôn', devanagari: 'एखन', tamil: 'ஏகோன்', meaning: 'Now' },
    { category: 'Daily', bengali: 'বাড়ি', roman: 'bāṛi', devanagari: 'बाड़ि', tamil: 'பாடி', meaning: 'Home' },
    { category: 'Daily', bengali: 'কাজ', roman: 'kāj', devanagari: 'काज', tamil: 'காஜ்', meaning: 'Work' },
    { category: 'Daily', bengali: 'খাবার', roman: 'khābār', devanagari: 'खाबार', tamil: 'காபார்', meaning: 'Food' },
    { category: 'Daily', bengali: 'জল', roman: 'jôl', devanagari: 'जल', tamil: 'ஜொல்', meaning: 'Water' },
    { category: 'Daily', bengali: 'রাস্তা', roman: 'rāstā', devanagari: 'रास्ता', tamil: 'ராஸ்தா', meaning: 'Road' },

    { category: 'Groceries', bengali: 'চাল', roman: 'cāl', devanagari: 'चाल', tamil: 'சால்', meaning: 'Rice' },
    { category: 'Groceries', bengali: 'ডাল', roman: 'ḍāl', devanagari: 'डाल', tamil: 'டால்', meaning: 'Lentils' },
    { category: 'Groceries', bengali: 'তেল', roman: 'tel', devanagari: 'तेल', tamil: 'தேல்', meaning: 'Oil' },
    { category: 'Groceries', bengali: 'নুন', roman: 'nun', devanagari: 'नून', tamil: 'நூன்', meaning: 'Salt' },
    { category: 'Groceries', bengali: 'চিনি', roman: 'cini', devanagari: 'चिनी', tamil: 'சினி', meaning: 'Sugar' },
    { category: 'Groceries', bengali: 'দুধ', roman: 'dudh', devanagari: 'दूध', tamil: 'தூத்', meaning: 'Milk' },
    { category: 'Groceries', bengali: 'আলু', roman: 'ālu', devanagari: 'आलू', tamil: 'ஆலு', meaning: 'Potato' },
    { category: 'Groceries', bengali: 'পেঁয়াজ', roman: 'pẽẏāj', devanagari: 'प्याज़', tamil: 'பேயாஜ்', meaning: 'Onion' },
    { category: 'Groceries', bengali: 'টমেটো', roman: 'ṭomeṭo', devanagari: 'टोमेटो', tamil: 'டொமேடோ', meaning: 'Tomato' },
    { category: 'Groceries', bengali: 'সবজি', roman: 'sôbji', devanagari: 'सब्ज़ी', tamil: 'சொப்ஜி', meaning: 'Vegetables' },

    { category: 'Worship', bengali: 'মন্দির', roman: 'môndir', devanagari: 'मन्दिर', tamil: 'மொந்திர்', meaning: 'Temple' },
    { category: 'Worship', bengali: 'পূজা', roman: 'pūjā', devanagari: 'पूजा', tamil: 'பூஜா', meaning: 'Worship' },
    { category: 'Worship', bengali: 'প্রসাদ', roman: 'prôśād', devanagari: 'प्रसाद', tamil: 'ப்ரொஷாத்', meaning: 'Prasadam' },
    { category: 'Worship', bengali: 'ভক্তি', roman: 'bhôkti', devanagari: 'भक्ति', tamil: 'பொக்தி', meaning: 'Devotion' },
    { category: 'Worship', bengali: 'গান', roman: 'gān', devanagari: 'गान', tamil: 'கான்', meaning: 'Song' },
    { category: 'Worship', bengali: 'শান্তি', roman: 'śānti', devanagari: 'शान्ति', tamil: 'ஶாந்தி', meaning: 'Peace' }
  ],

  sentences: [
    { category: 'Greetings', bengali: 'নমস্কার। আপনি কেমন আছেন?', roman: 'Nômôskār. Āpni kemon āchen?', devanagari: 'नमस्कार। आपनि केमोन आछेन?', tamil: 'நமஷ்கார். ஆப்னி கேமோன் ஆச்சேன்?', meaning: 'Namaskaram. How are you?' },
    { category: 'Greetings', bengali: 'আমি ভালো আছি।', roman: 'Āmi bhālo āchi.', devanagari: 'आमि भालो आछि।', tamil: 'ஆமி பாலோ ஆச்சி.', meaning: 'I am fine.' },
    { category: 'Greetings', bengali: 'আপনার নাম কি?', roman: 'Āpnār nām ki?', devanagari: 'आपनार नाम कि?', tamil: 'ஆப்னார் நாம் கி?', meaning: 'What is your name?' },
    { category: 'Greetings', bengali: 'আমার নাম বৈদ্যনাথন।', roman: 'Āmār nām Vaidyanāthan.', devanagari: 'आमार नाम वैद्यनाथन।', tamil: 'ஆமார் நாம் வைத்யநாதன்.', meaning: 'My name is Vaidyanathan.' },
    { category: 'Greetings', bengali: 'আপনার সঙ্গে দেখা হয়ে ভালো লাগলো।', roman: 'Āpnār sôṅge dekhā hoẏe bhālo lāglo.', devanagari: 'आपनार संगे देखा होये भालो लागलो।', tamil: 'ஆப்னார் சொங்கே தேகா ஹோயே பாலோ லாக்லோ.', meaning: 'Nice to meet you.' },

    { category: 'Daily', bengali: 'আপনি কোথায় যাচ্ছেন?', roman: 'Āpni kothāẏ jāchhen?', devanagari: 'आपनि कोथाय जाछेन?', tamil: 'ஆப்னி கோதாய் ஜாச்சேன்?', meaning: 'Where are you going?' },
    { category: 'Daily', bengali: 'আমি বাড়ি যাচ্ছি।', roman: 'Āmi bāṛi jāchhi.', devanagari: 'आमि बाड़ि जाछि।', tamil: 'ஆமி பாடி ஜாச்சி.', meaning: 'I am going home.' },
    { category: 'Daily', bengali: 'আমি একটু বাংলা শিখছি।', roman: 'Āmi ekṭu bāṅlā śikhchi.', devanagari: 'आमि एक्टु बांग्ला शिखछि।', tamil: 'ஆமி எக்டு பாங்லா ஶிக்ச்சி.', meaning: 'I am learning a little Bengali.' },
    { category: 'Daily', bengali: 'আস্তে বলুন, দয়া করে।', roman: 'Āste bolun, dôẏā kore.', devanagari: 'आस्ते बोलुन, दया करे।', tamil: 'ஆஸ்தே போலுன், தொயா கொரே.', meaning: 'Please speak slowly.' },
    { category: 'Daily', bengali: 'আবার বলুন, দয়া করে।', roman: 'Ābār bolun, dôẏā kore.', devanagari: 'आबार बोलुन, दया करे।', tamil: 'ஆபார் போலுன், தொயா கொரே.', meaning: 'Please say it again.' },
    { category: 'Daily', bengali: 'আমি বুঝতে পারছি না।', roman: 'Āmi bujhte pārchi nā.', devanagari: 'आमि बुझते पारछि ना।', tamil: 'ஆமி புஜ்தே பார்ச்சி நா.', meaning: 'I do not understand.' },
    { category: 'Daily', bengali: 'এটার মানে কি?', roman: 'Eṭār māne ki?', devanagari: 'एटार माने कि?', tamil: 'ஏடார் மானே கி?', meaning: 'What does this mean?' },

    { category: 'Shopping', bengali: 'এটার দাম কত?', roman: 'Eṭār dām kôto?', devanagari: 'एटार दाम कतो?', tamil: 'ஏடார் தாம் கொதோ?', meaning: 'How much does this cost?' },
    { category: 'Shopping', bengali: 'এক কিলো চাল দিন।', roman: 'Ek kilo cāl din.', devanagari: 'एक किलो चाल दिन।', tamil: 'ஏக் கிலோ சால் தின்.', meaning: 'Please give me one kilogram of rice.' },
    { category: 'Shopping', bengali: 'আমার আলু আর পেঁয়াজ চাই।', roman: 'Āmār ālu ār pẽẏāj cāi.', devanagari: 'आमार आलू आर प्याज़ चाइ।', tamil: 'ஆமார் ஆலு ஆர் பேயாஜ் சாய்.', meaning: 'I need potatoes and onions.' },
    { category: 'Shopping', bengali: 'আর কিছু লাগবে না।', roman: 'Ār kichu lāgbe nā.', devanagari: 'आर किछु लागबे ना।', tamil: 'ஆர் கிச்சு லாக்பே நா.', meaning: 'I do not need anything else.' },

    { category: 'Travel', bengali: 'মন্দির কোথায়?', roman: 'Môndir kothāẏ?', devanagari: 'मन्दिर कोथाय?', tamil: 'மொந்திர் கோதாய்?', meaning: 'Where is the temple?' },
    { category: 'Travel', bengali: 'স্টেশন কত দূর?', roman: 'Sṭeśon kôto dūr?', devanagari: 'स्टेशन कतो दूर?', tamil: 'ஸ்டேஷன் கொதோ தூர்?', meaning: 'How far is the station?' },
    { category: 'Travel', bengali: 'আমাকে এখানে নামিয়ে দিন।', roman: 'Āmāke ekhāne nāmiẏe din.', devanagari: 'आमाके एखाने नामिये दिन।', tamil: 'ஆமாகே ஏகானே நாமியே தின்.', meaning: 'Please drop me here.' },

    { category: 'Worship', bengali: 'মায়ের প্রসাদ কোথায় পাওয়া যাবে?', roman: 'Māẏer prôśād kothāẏ pāoẏā jābe?', devanagari: 'मायेर प्रसाद कोथाय पावा जाबे?', tamil: 'மாயேர் ப்ரொஷாத் கோதாய் பாவா ஜாபே?', meaning: 'Where can I receive Mother’s prasadam?' },
    { category: 'Worship', bengali: 'এই গানটি খুব সুন্দর।', roman: 'Ei gānṭi khub sundôr.', devanagari: 'एइ गानटि खूब सुन्दर।', tamil: 'ஏய் கான்டி கூப் சுந்தோர்.', meaning: 'This song is very beautiful.' },
    { category: 'Worship', bengali: 'মা আমাদের ভক্তি দিন।', roman: 'Mā āmāder bhôkti din.', devanagari: 'माँ आमादेर भक्ति दिन।', tamil: 'மா ஆமாதேர் பொக்தி தின்.', meaning: 'Mother, grant us devotion.' }
  ]
};
